config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes do
    member do
      put 'like',    to: 'recipes#upvote'
      put 'dislike', to: 'recipes#downvote'
    end
  end

  resources :users
  get 'tags/:tag', to: 'recipes#index', as: 'tag'

  root 'recipes#index'

end

app/models/concerns/capitalize_concern.rb
module CapitalizeConcern
  extend ActiveSupport::Concern

  included do
    before_create :capitalize_name

    def capitalize_name
      name.capitalize!
    end
  end
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  has_many :directions
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user
  acts_as_votable

  # NESTED INGREDIENTS AND DIRECTIONS
  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  accepts_nested_attributes_for :directions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true

  validates :title, :image, presence: true

  # IMAGE
  has_attached_file :image, styles: { medium: '400x400#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  scope :by_dates, -> { order(:created_at).reverse_order }

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).recipes
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include CapitalizeConcern
  has_many :taggings
  has_many :recipes, through: :taggings

  def self.counts
    select('name, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  include CapitalizeConcern
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
  validates :name, presence:true, uniqueness: true
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all.order('created_at ASC')

    @recipes = if params[:tag]
                 Recipe.tagged_with(params[:tag])
               else
                 Recipe.all
               end
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
  end

  def edit
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recette créée avec succès !' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recette supprimée.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @recipe.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @recipe.downvote_by current_user
    redirect_to :back
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :all_tags, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def tag_links(tags)
    tags.split(',').map { |tag| link_to tag.strip, tag_path(tag.strip) }.join(' ')
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Om nom nom...
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .navbar_container
      .navbar-brand= link_to "Om nom nom...", root_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Nouvelle recette", new_recipe_path
          %li= link_to "Deconnexion", destroy_user_session_path, method: :delete
          %li= link_to "Mon profil", user_path(current_user)
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{"data-target" => "#ModalSignUp", "data-toggle" => "modal", :type => "button"} Inscription
            #ModalSignUp.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog{:role => "document"}
                .modal-content.signup-content
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  .row
                    = render "devise/registrations/new"
          %li
            %a{"data-target" => "#ModalSignIn", "data-toggle" => "modal", :type => "button"} Connexion
            #ModalSignIn.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog{:role => "document"}
                .modal-content.signin-content
                  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                  .row
                    = render "devise/sessions/new"


  .container
    - flash.each do |name, msg|
      .alert
        = content_tag :div, msg
    = yield

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :step, input_html: { class: 'form-input form-control' }
    = link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: {multipart: true} do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count
        prohibited this recipe from being saved:
      %ul
        - @recipe.errors.full_messages.each do |message|
          %li= message
  .row
    .panel-body
      = f.input :title, input_html: {class: 'form-control'}
      = f.input :description, placeholder: 'Dites nous ce que vous aimez dans cette recette ? où l\'avez-vous découverte ? avec quoi l\'accompagnée vous ? ...', input_html: {class: 'form-control'}
      = f.input :image, input_html: {class: 'form-control'}
      = f.input :all_tags, label: 'Tags', input_html: {class: 'form-control'}
      / = f.input :all_tags, label: 'Tags', collection: Tag.all, input_html: {multiple: true, class: 'form-control'}

      .tag-wrapper


        /   %input{:type => "checkbox"}/
        /   %label{:for => ""} Végétalien
        /   %i.fa.fa-plus
        /   %i.fa.fa-check
        / .tag
        /   %input{:type => "checkbox"}/
        /   %label{:for => ""} Diet
        /   %i.fa.fa-plus
        /   %i.fa.fa-check
        / .tag
        /   %input{:type => "checkbox"}/
        /   %label{:for => ""} Healthy
        /   %i.fa.fa-plus
        /   %i.fa.fa-check
    .row
      .col-md-6
        %h3 Ingredients
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields', f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

      .col-md-6
        %h3 Directions
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .links
            = link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

      = f.button :submit, class: "btn btn-primary"

%script{:src => "https://use.fontawesome.com/6d77a862a3.js"}

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :name, input_html: { class: 'form-input form-control' }
    = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.haml
- @recipes.each_slice(4) do |recipes|
  .row.row_recipe_index
    - recipes.each do |recipe|
      .col-md-3
        .recipe
          .image_wrapper
            = link_to recipe_path(recipe) do
              = image_tag recipe.image.url(:medium)
              %h2= recipe.title
          .tags
            = tag_links(recipe.all_tags).html_safe
          .btn-group
            = link_to like_recipe_path(recipe), method: :put, class: "btn" do
              %span.glyphicon.glyphicon-heart-empty
              \#{recipe.get_upvotes.size}
            = link_to dislike_recipe_path(recipe), method: :put, class: "btn" do
              %span.glyphicon.glyphicon-thumbs-down
              \#{recipe.get_downvotes.size}

%script{:src => "https://use.fontawesome.com/6d77a862a3.js"}

app/views/recipes/new.html.haml
%h1 Nouvelle recette

= render 'form'

= link_to 'Toutes les recettes', recipes_path, class: "btn btn-default"

app/views/recipes/show.html.haml
.main_content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium), class:"recipe_image"
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        .tags
          = tag_links(@recipe.all_tags).html_safe
        %p.description= @recipe.description
        %p
          Publiée par
          = @recipe.user.name

  .row
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient.name

    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do |direction|
            %li= direction.step

  .row
    .col-md-12
      = link_to 'Toutes les recettes', recipes_path, class: "btn btn-default"
      - if user_signed_in?
        = link_to 'Modifier', edit_recipe_path(@recipe), class: "btn btn-default"
        = link_to 'Supprimer', recipe_path(@recipe), method: :delete, data: {confirm:"Cette recette sera  définitivement supprimée"}, class: "btn btn-default"

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice= notice
.container
  %h1.user_name= @user.name
#exTab1.container.tab
  %ul.nav.nav-pills
    %li.active
      %a{"data-toggle" => "tab", :href => "#published"}
        .value
          = @user.recipes.count
        recettes publiées
    %li
      %a{"data-toggle" => "tab", :href => "#favorites"}
        .value
          0
        recettes favorites
    %li
      %a{"data-toggle" => "tab", :href => "#likes"}
        .value
          = @user.votes.count
        mention j'aime
    %li
      %a{"data-toggle" => "tab", :href => "#done"}
        .value
          0
        recettes réalisées

  .tab-content.clearfix
    #published.tab-pane.active
      - @user.recipes.each_slice(4) do |recipes|
        .row
          - recipes.each do |recipe|
            .col-md-3
              .recipe
                .image_wrapper
                  = link_to recipe do
                    = image_tag recipe.image.url(:medium)
                %h2= link_to recipe.title, recipe
                .tags
                  = tag_links(recipe.all_tags).html_safe
                .btn-group
                  = link_to like_recipe_path(recipe), method: :put, class: "btn" do
                    %span.glyphicon.glyphicon-heart-empty
                    \#{recipe.get_upvotes.size}
                  = link_to dislike_recipe_path(recipe), method: :put, class: "btn" do
                    %span.glyphicon.glyphicon-thumbs-down
                    \#{recipe.get_downvotes.size}

    #favorites.tab-pane
      %h3 Recettes favorites
    #likes.tab-pane
      - @user.recipes.each_slice(4) do |recipes|
        .row
          - recipes.each do |recipe|
            .col-md-3
              .recipe
                .image_wrapper
                  = link_to recipe do
                    = image_tag recipe.image.url(:medium)
                %h2= link_to recipe.title, recipe
                .tags
                  = tag_links(recipe.all_tags).html_safe
                .btn-group
                  = link_to like_recipe_path(recipe), method: :put, class: "btn" do
                    %span.glyphicon.glyphicon-heart-empty
                    \#{recipe.get_upvotes.size}
                  = link_to dislike_recipe_path(recipe), method: :put, class: "btn" do
                    %span.glyphicon.glyphicon-thumbs-down
                    \#{recipe.get_downvotes.size}
    #done.tab-pane
      %h3 Recettes réalisées



= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}



%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"}
%script{:src => "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}